# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40cf6e2b40c0cd88de307ee23cc5beed90e7eff7bcbfef7a2af3d963eca2f3a930128e761823a808aac145e3cfee3dac29d51372d62be3e63dc6b1a997a1cb03

test:
  secret_key_base: fa1033e5047889192e31bb17a0f02ba20ed22c4f2f864ed82529a2048e8309036afe40aa4be52d3899f274511a7bf371a0aa0c778f689dffa9392f2cab2b91fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
